//package com.graby.store.admin.print;
//import javax.swing.JApplet;
//import javax.swing.JOptionPane;
//
//
//import net.sf.jasperreports.engine.JasperPrint;
//
//
//public class PickApplet extends JApplet {
//
//	private static final long serialVersionUID = -4333412311016781823L;
//
//	/**
//	 *
//	 */
//	private JasperPrint jasperPrint;
//	private PickData pickData;
//
//	/** Creates new form AppletViewer */
//	public PickApplet()
//	{
//		initComponents();
//		pickData = new PickData();
//	}
//
//
//	/** This method is called from within the constructor to
//	 * initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is
//	 * always regenerated by the Form Editor.
//	 */
//	private void initComponents() {//GEN-BEGIN:initComponents
//		pnlMain = new javax.swing.JPanel();
//		btnPrint = new javax.swing.JButton();
//		btnView = new javax.swing.JButton();
//
//		btnPrint.setText("批量打印拣货单");
//		btnPrint.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				btnPrintActionPerformed(evt);
//			}
//		});
//
//		pnlMain.add(btnPrint);
//
//		btnView.setText("拣货单打印预览");
//		btnView.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				btnViewActionPerformed(evt);
//			}
//		});
//
//		pnlMain.add(btnView);
//
//		getContentPane().add(pnlMain, java.awt.BorderLayout.WEST);
//
//	}//GEN-END:initComponents
//
//	protected void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
//		// Add your handling code here:
//		JOptionPane.showMessageDialog(this, "Source URL not specified");
//	}//GEN-LAST:event_btnViewActionPerformed
//
//	protected void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
//		JOptionPane.showMessageDialog(this, "KK Print processing ..");
//		// Add your handling code here:
////		if (url != null)
////		{
////			if (jasperPrint == null)
////			{
////				try
////				{
////					jasperPrint = (JasperPrint)JRLoader.loadObject(url);
////				}
////				catch (Exception e)
////				{
////					StringWriter swriter = new StringWriter();
////					PrintWriter pwriter = new PrintWriter(swriter);
////					e.printStackTrace(pwriter);
////					JOptionPane.showMessageDialog(this, swriter.toString());
////				}
////			}
////			
////			if (jasperPrint != null)
////			{				
////				final JasperPrint print = jasperPrint;
////				
////				Thread thread = new Thread
////					(
////						new Runnable()
////						{
////							public void run()
////							{
////								try 
////								{
////									JasperPrintManager.printReport(print, true);
////								}
////								catch (Exception e) 
////								{
////									StringWriter swriter = new StringWriter();
////									PrintWriter pwriter = new PrintWriter(swriter);
////									e.printStackTrace(pwriter);
////									JOptionPane.showMessageDialog(null, swriter.toString());
////								}
////							}
////						}
////					);
////				
////				thread.start();
////			}
////			else
////			{
////				JOptionPane.showMessageDialog(this, "Empty report.");
////			}
////		}
////		else
////		{
////			JOptionPane.showMessageDialog(this, "Source URL not specified");
////		}
//	}//GEN-LAST:event_btnPrintActionPerformed
//	
//	
//	// Variables declaration - do not modify//GEN-BEGIN:variables
//	private javax.swing.JPanel pnlMain;
//	private javax.swing.JButton btnView;
//	private javax.swing.JButton btnPrint;
//	// End of variables declaration//GEN-END:variables
//
//}
